steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/onyx-system-prod/onyx-images/backend:$COMMIT_SHA'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/onyx-system-prod/onyx-images/backend:$COMMIT_SHA'

  # Step 3: Deploy to Cloud Run, using the connection string from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ums-api'
      - '--image=asia-south1-docker.pkg.dev/onyx-system-prod/onyx-images/backend:$COMMIT_SHA'
      - '--region=asia-south1'
      - '--port=8080'
      - '--allow-unauthenticated'
      - '--set-env-vars=ConnectionStrings__DefaultConnection=$$DB_CONNECTION_STRING' # Use the secret
    secretEnv: ['DB_CONNECTION_STRING']

# This section makes the secret available to the steps above
availableSecrets:
  secretManager:
  - versionName: projects/onyx-system-prod/secrets/ums-db-connection-string/versions/latest
    env: 'DB_CONNECTION_STRING'

# Tell Cloud Build which images to store
images:
  - 'asia-south1-docker.pkg.dev/onyx-system-prod/onyx-images/backend:$COMMIT_SHA'