steps:
    # Step 01: Build the Docker image    
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/onyx-system-prod/onyx-images/backend:$COMMIT_SHA'
      - '.'
    id: 'Build Docker Image'

    # Step 02: Push the docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/onyx-system-prod/onyx-images/backend:$COMMIT_SHA'
    id: 'Push to Artifact registry'

    # Step 03: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ums-api' # The name of the Cloud Run service
      - '--image=asia-south1-docker.pkg.dev/onyx-system-prod/onyx-images/backend:$COMMIT_SHA'
      - '--region=asia-south1'
      - '--port=8080'
      - '--allow-unauthenticated'
      - '--set-env-vars=ConnectionStrings__DefaultConnection=Server=192.168.36.151;Database=ums_db;User ID=sa;Password=sqlserverlptp;TrustServerCertificate=True'
    id: "Deploy to Cloud Run"

# Tell Cloud Build which images to store in Artifact Registry after the build
images:
  - 'asia-south1-docker.pkg.dev/onyx-system-prod/onyx-images/backend:$COMMIT_SHA'